#! /bin/bash

rm -f *.o
rm -f *~
rm -f *#

rm -f src/*.o
rm -f src/*~
rm -f src/*#

rm -f src/type_file/*.o
rm -f src/type_file/*~
rm -f src/type_file/*#

rm -f src/display/*.o
rm -f src/display/*~
rm -f src/display/*#

rm -f src/flag/*.o
rm -f src/flag/*~
rm -f src/flag/*#

rm -f src/concat_argu/*.o
rm -f src/concat_argu/*~
rm -f src/concat_argu/*#

rm -f src/determinate/*.o
rm -f src/determinate/*~
rm -f src/determinate/*#

rm -f src/comparaison/*.o
rm -f src/comparaison/*~
rm -f src/comparaison/*#

rm -f src/sort/*.o
rm -f src/sort/*~
rm -f src/sort/*#

rm -f src/create/*.o
rm -f src/create/*~
rm -f src/create/*#
